import type { AnalysisResult, ResumeData } from "@/types";
import { extractKeywords } from "./utils";

export async function callAI<T>(system:string,user:string,fallback:T):Promise<T>{
  const key=process.env.OPENROUTER_API_KEY; if(!key) return fallback;
  try{ const res=await fetch("https://openrouter.ai/api/v1/chat/completions",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${key}`,"HTTP-Referer":process.env.NEXT_PUBLIC_SITE_URL||"http://localhost:3000","X-Title":"Reva ATS Resume Optimizer"},body:JSON.stringify({model:process.env.OPENROUTER_MODEL||"google/gemma-4-31b-it:free",messages:[{role:"system",content:system},{role:"user",content:user}],response_format:{type:"json_object"}})});
  if(!res.ok) return fallback; const data=await res.json(); const text=data.choices?.[0]?.message?.content; return JSON.parse(text) as T; }catch{return fallback;}
}
export function fallbackAnalysis(jd:string,resume:string):AnalysisResult{ const jdKeys=extractKeywords(jd); const found=jdKeys.filter(k=>resume.toLowerCase().includes(k)); const missing=jdKeys.filter(k=>!found.includes(k)); const keyword=Math.round((found.length/Math.max(jdKeys.length,1))*40); const quantified=(resume.match(/\d+%?|\$|rs|inr|lpa/gi)||[]).length>2?13:8; const breakdown={keyword_match:keyword,section_headers:resume.match(/summary|experience|skills|education/i)?18:10,file_format:15,quantified_items:quantified,clean_formatting:9}; const score=Object.values(breakdown).reduce((a,b)=>a+b,0); return {ats_score:score,breakdown,keywords_found:found,keywords_missing:missing,quick_wins:["Add missing JD keywords naturally","Use standard section headers","Quantify impact in bullets"],improvement_tips:missing.slice(0,5).map(k=>`Add ${k} where it truthfully matches your work.`)} }
export function fallbackResume(resume:string,jd:string):ResumeData&{ats_score_after:number;keywords_added:string[]}{ const keys=extractKeywords(jd).slice(0,10); return {contact:{name:"Your Name",email:"you@example.com",phone:"+91 00000 00000",linkedin:"linkedin.com/in/you",location:"India"},summary:`Results-driven professional with experience across ${keys.slice(0,4).join(", ")} and measurable delivery in fast-paced teams.`,experience:[{title:"Relevant Role",company:"Current Company",location:"India",dates:"2022 - Present",bullets:[`Delivered business impact using ${keys.slice(0,3).join(", ")} while improving process quality.`,`Collaborated with cross-functional teams to ship reliable solutions aligned to job requirements.`,`Converted resume facts into ATS-friendly language without adding unverified claims.`]}],skills:keys.length?keys:["Communication","Project Delivery","Analysis"],education:[{degree:"Degree",school:"University",year:"Year"}],certifications:[],ats_score_after:95,keywords_added:keys}; }
