"use client";
import { useEffect, useState } from "react";
import Link from "next/link";

type Stats={preview:boolean;totals:{members:number;free:number;pro:number;premium:number;owners:number;activeSubscriptions:number;monthlyRevenue:number;analyses:number};recentUsers:{email:string;name?:string;plan:string;created_at:string;analyses_used?:number}[];subscriptions:{id?:string;plan?:string;status?:string;period_end?:string}[]};
function Stat({label,value}:{label:string;value:string|number}){return <div className="stat"><small>{label}</small><b>{value}</b></div>}

export default function Owner(){
  const [stats,setStats]=useState<Stats|null>(null);const [error,setError]=useState("");
  useEffect(()=>{fetch("/api/owner/stats").then(async r=>{const raw=await r.text();const d=raw?JSON.parse(raw):{};if(!r.ok) throw new Error(d.message||"Owner access required");setStats(d)}).catch(e=>setError(e instanceof Error?e.message:"Owner access required"));},[]);
  return <><nav className="nav"><Link className="brand" href="/dashboard">Reva Owner</Link><div className="navlinks"><Link href="/dashboard">Dashboard</Link><Link href="/pricing">Pricing</Link></div></nav><main className="ownerPage"><h1>Owner Dashboard</h1>{error&&<div className="card"><h2>Access blocked</h2><p>{error}</p><p>Login with paletiganesh456@gmail.com or paletiganesh218@gmail.com.</p><Link className="btn" href="/login">Login as owner</Link></div>}{!stats&&!error&&<p>Loading owner stats...</p>}{stats&&<><p>{stats.preview?"Preview mode: connect Supabase to see real members and subscriptions.":"Live Supabase stats"}</p><div className="statGrid"><Stat label="Members" value={stats.totals.members}/><Stat label="Free" value={stats.totals.free}/><Stat label="Pro" value={stats.totals.pro}/><Stat label="Premium" value={stats.totals.premium}/><Stat label="Active subscriptions" value={stats.totals.activeSubscriptions}/><Stat label="Monthly revenue" value={`Rs ${stats.totals.monthlyRevenue}`}/></div><section className="card"><h2>Recent Members</h2><div className="table"><div className="thead"><span>Email</span><span>Name</span><span>Plan</span><span>Joined</span></div>{stats.recentUsers.map(u=><div className="trow" key={u.email}><span>{u.email}</span><span>{u.name||"-"}</span><span>{u.plan}</span><span>{new Date(u.created_at).toLocaleDateString()}</span></div>)}</div></section><section className="card"><h2>Subscription Monitor</h2><p>Active: {stats.totals.activeSubscriptions} | Revenue: Rs {stats.totals.monthlyRevenue}/month</p><p>Razorpay wiring is intentionally paused until you provide payment details.</p></section></>}</main></>;
}
